from .procedure import ProcedureSerializer
from .medicineFlexVarUpdate import MedicineFlexVarUpdateSerializer
from .procedureFlex import ProcedureFlexSerializer
from .public_medicine import PublicMedicineSerializer
from .medicine import MedicineSerializer
from .authorisationFlexVarUpdate import AuthorisationFlexVarUpdateSerializer
from .authorisation import AuthorisationSerializer
from .lookupSerializers import LookupStatusSerializer, LookupAtccodeSerializer, LookupLegalscopeSerializer, LookupLegalbasisSerializer, LookupActiveSubstanceSerializer, LookupMedicinetypeSerializer, LookupRapporteurSerializer