decision = "dec"
decision_initial = "dec_initial"
annex = "anx"
annex_initial = "anx_initial"
epar = "epar"
omar = "omar"
web = "web"
filedates = "filedates"

atc_code = [web]                                            # ATC code (chemical substance level 5)
atc_name_l1 = [web]                                         # ATC name (level 1)*
atc_name_l2 = [web]                                         # ATC name (level 2)*
atc_name_l3 = [web]                                         # ATC name (level 3)*
atc_name_l4 = [web]                                         # ATC name (level 4)*
active_substance = [web, decision_initial]                               # Active substance
eu_nas = [decision_initial]                                           # EU new active substance
ema_procedure_start_initial = [epar] # Initial EMA procedure start date
chmp_opinion_date = [epar]                     # Initial EMA (CHMP) opinion date
eu_aut_date = [web, decision_initial]                                 # Initial EU authorisation date
eu_aut_type_initial = [decision_initial, annex_initial, web]                 # Initial type of EU authorisation*
eu_aut_type_current = [web]                 # Current type of EU authorisation*
eu_brand_name_initial = [decision_initial]             # Initial EU brand name*
eu_pnumber = [web]                                   # EU product number
eu_pnumber_id = [web]                            # EU product number ID
eu_legal_basis = [epar]                          # EU legal basisz
aut_url = [filedates]                                         # URL to EU authorisation decision
smpc_url = [filedates]                                       # URL to EU authorisation annex
epar_url = [filedates]                                       # URL to EMA initial authorisation EPAR
eu_atmp = [decision]                                         # EU ATMP
eu_med_type = [annex_initial]                                 # EU type of medicine
eu_aut_status = [web, web]                             # EU authorisation status
# eu_brand_name = [web]                             # EU brand name*
eu_brand_name_current = [web]             # Current EU brand name
# eu_brand_name_history = "eu_brand_name_history"             # History of EU brand names*
ema_number = [web]                                   # EMA application number
ema_number_id = [web]                             # EMA application number ID
ema_number_certainty = [web]               # EMA application number certainty
ema_number_check = [web]                      # EMA application number check
# eu_mah = "eu_mah"                                           # EU marketing authorisation holder*
eu_mah_current = [web]                           # Current EU marketing authorisation holder*
eu_mah_initial = [decision_initial]                           # Initial EU marketing authorisation holder
eu_mah_history = [web]                           # History of EU marketing authorisation holders
eu_prime_initial = [epar]                       # EU Priority Medicine at authorisation
eu_prime_history = [epar]                       # History of EU Priority Medicine
eu_od_initial = [decision_initial]                             # EU orphan designation at au,thorisation
eu_od_history = [decision] #?                             # Histo,ry of EU orphan design,ation
ema_url = [filedates]                                         # URL to EMA medicinal product p,age,
ec_url = [filedates]                                          # URL to EC medicinal product page,
ema_rapp = [epar]                                       # EMA rapporteur for initial a,uthorisat,ion
ema_corapp = [epar]                                   # EMA co-rapporteur for in,itial aut,horisation
eu_accel_assess_g = [epar]                     # EU accelerated assessment granted
eu_accel_assess_m = [epar]                     # EU accelerated assessment maintained
# assess_time_days_total = "assess_time_days_total"           # Duration of initial EU authorisation assessment procedure (total days)
# assess_time_days_active = "assess_time_days_active"         # Duration of initial EU authorisation assessment procedure (active days)
# assess_time_days_cstop = "assess_time_days_cstop"           # Duration of initial EU authorisation assessment procedure (clock-stop days)
# ec_decision_time_days = "ec_decision_time_days"             # EC decision time (days)
ema_reexamination = [epar]                     # EMA re-examination performed
# eu_orphan_con_initial = "eu_orphan_con_initial"             # Initial EU orphan conditions
eu_orphan_con_current = [web]             # Current EU orphan conditions
eu_referral = [web]                                 # EU referral
eu_suspension = [web]                             # EU suspension
omar_url = [filedates]                                       # URL to orphan maintanance assessment report
odwar_url = [filedates]                                     # URL to orphan designation withdrawal assessment report
eu_od_number = [web]                               # EU orphan designation number
ema_od_number = [web]                             # EMA orphan designation number
eu_od_con = [web]                                           # EU orphan designation condition
eu_od_date = [filedates]                                   # EU orphan designation date
eu_od_pnumber = [web]                             # EU product number for orphan designation
eu_od_sponsor = [web]                                       # Sponsor for EU orphan designation
# eu_od_comp_date = "eu_od_comp_date"                       # COMP decision date (for EU orphan designation)