# string definitions of all to scrape attributes for reducing hardcoded strings

atc_code = "atc_code"                                       # ATC code (chemical substance level 5)
atc_name_l1 = "atc_name_l1"                                 # ATC name (level 1)*
atc_name_l2 = "atc_name_l2"                                 # ATC name (level 2)*
atc_name_l3 = "atc_name_l3"                                 # ATC name (level 3)*
atc_name_l4 = "atc_name_l4"                                 # ATC name (level 4)*
active_substance = "active_substance"                       # Active substance
eu_nas = "eu_nas"                                           # EU new active substance
ema_procedure_start_initial = "ema_procedure_start_initial" # Initial EMA procedure start date
chmp_opinion_date = "chmp_opinion_date"                     # Initial EMA (CHMP) opinion date
eu_aut_date = "eu_aut_date"                                 # Initial EU authorisation date
eu_aut_type_initial = "eu_aut_type_initial"                 # Initial type of EU authorisation*
eu_aut_type_current = "eu_aut_type_current"                 # Current type of EU authorisation*
eu_brand_name_initial = "eu_brand_name_initial"             # Initial EU brand name*
eu_pnumber = "eu_pnumber"                                   # EU product number
eu_pnumber_id = "eu_pnumber_id"                             # EU product number ID
eu_legal_basis = "eu_legal_basis"                           # EU legal basis
aut_url = "aut_url"                                         # URL to EU authorisation decision
smpc_url = "smpc_url"                                       # URL to EU authorisation annex
epar_url = "epar_url"                                       # URL to EMA initial authorisation EPAR
eu_atmp = "eu_atmp"                                         # EU ATMP
eu_med_type = "eu_med_type"                                 # EU type of medicine
eu_aut_status = "eu_aut_status"                             # EU authorisation status
eu_brand_name = "eu_brand_name"                             # EU brand name*
eu_brand_name_current = "eu_brand_name_current"             # Current EU brand name
eu_brand_name_history = "eu_brand_name_history"             # History of EU brand names*
ema_number = "ema_number"                                   # EMA application number
ema_number_id = "ema_number_id"                             # EMA application number ID
ema_number_certainty = "ema_number_certainty"               # EMA application number certainty
ema_number_check = "ema_number_check"                       # EMA application number check
eu_mah = "eu_mah"                                           # EU marketing authorisation holder*
eu_mah_current = "eu_mah_current"                           # Current EU marketing authorisation holder*
eu_mah_initial = "eu_mah_initial"                           # Initial EU marketing authorisation holder
eu_mah_history = "eu_mah_history"                           # History of EU marketing authorisation holders
eu_prime_initial = "eu_prime_initial"                       # EU Priority Medicine at authorisation
eu_prime_history = "eu_prime_history"                       # History of EU Priority Medicine
eu_od_initial = "eu_od_initial"                             # EU orphan designation at au,thorisation
eu_od_history = "eu_od_history"                             # Histo,ry of EU orphan design,ation
ema_url = "ema_url"                                         # URL to EMA medicinal product p,age,
ec_url = "ec_url"                                           # URL to EC medicinal product page,
ema_rapp = "ema_rapp"                                       # EMA rapporteur for initial a,uthorisat,ion
ema_corapp = "ema_corapp"                                   # EMA co-rapporteur for in,itial aut,horisation
eu_accel_assess_g = "eu_accel_assess_g"                     # EU accelerated assessment granted
eu_accel_assess_m = "eu_accel_assess_m"                     # EU accelerated assessment maintained
assess_time_days_total = "assess_time_days_total"           # Duration of initial EU authorisation assessment procedure (total days)
assess_time_days_active = "assess_time_days_active"         # Duration of initial EU authorisation assessment procedure (active days)
assess_time_days_cstop = "assess_time_days_cstop"           # Duration of initial EU authorisation assessment procedure (clock-stop days)
ec_decision_time_days = "ec_decision_time_days"             # EC decision time (days)
ema_reexamination = "ema_reexamination"                     # EMA re-examination performed
eu_orphan_con_initial = "eu_orphan_con_initial"             # Initial EU orphan conditions
eu_orphan_con_current = "eu_orphan_con_current"             # Current EU orphan conditions
eu_referral = "eu_referral"                                 # EU referral
eu_suspension = "eu_suspension"                             # EU suspension
omar_url = "omar_url"                                       # URL to orphan maintanance assessment report
odwar_url = "odwar_url"                                     # URL to orphan designation withdrawal assessment report
eu_od_number = "eu_od_number"                               # EU orphan designation number
ema_od_number = "ema_od_number"                             # EMA orphan designation number
eu_od_con = "eu_od_con"                                     # EU orphan designation condition
eu_od_date = "eu_od_date"                                   # EU orphan designation date
eu_od_pnumber = "eu_od_pnumber"                             # EU product number for orphan designation
eu_od_sponsor = "eu_od_sponsor"                             # Sponsor for EU orphan designation
eu_od_comp_date = "eu_od_comp_date"                         # COMP decision date (for EU orphan designation)

not_found = "NA | Not Found | Unkown"
