from models.atc_code import AtcCode
from models.component import Component
from models.legal_basis import LegalBasis
from models.legal_scope import LegalScope
from models.marketing_authorisation_holder import MarketingAuthorisationHolder
from models.medicine import Medicine
from models.medicine_name import MedicineName
from models.procedure import Procedure
from models.procedure_type import ProcedureType
from models.region import Region
from models.substance import Substance