# Generated by Django 4.0.4 on 2022-05-12 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lookupactivesubstance',
            fields=[
                ('activesubstance', models.CharField(db_column='ActiveSubstance', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lookupactivesubstance',
            },
        ),
        migrations.CreateModel(
            name='Lookupatccode',
            fields=[
                ('atccode', models.CharField(db_column='ATCCode', max_length=7, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lookupatccode',
            },
        ),
        migrations.CreateModel(
            name='Lookuplegalbasis',
            fields=[
                ('legalbasis', models.CharField(db_column='LegalBasis', max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lookuplegalbasis',
            },
        ),
        migrations.CreateModel(
            name='Lookuplegalscope',
            fields=[
                ('legalscope', models.CharField(db_column='LegalScope', max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lookuplegalscope',
            },
        ),
        migrations.CreateModel(
            name='Lookupmedicinetype',
            fields=[
                ('medicinetype', models.CharField(db_column='MedicineType', max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lookupmedicinetype',
            },
        ),
        migrations.CreateModel(
            name='Lookupproceduretype',
            fields=[
                ('proceduretype', models.CharField(db_column='ProcedureType', max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lookupproceduretype',
            },
        ),
        migrations.CreateModel(
            name='Lookuprapporteur',
            fields=[
                ('rapporteur', models.CharField(db_column='Rapporteur', max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lookuprapporteur',
            },
        ),
        migrations.CreateModel(
            name='Lookupstatus',
            fields=[
                ('status', models.CharField(db_column='Status', max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lookupstatus',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('eunumber', models.IntegerField(db_column='EUNumber', primary_key=True, serialize=False)),
                ('emanumber', models.CharField(blank=True, db_column='EMANumber', max_length=45, null=True)),
                ('newactivesubstance', models.IntegerField(blank=True, db_column='NewActiveSubstance', null=True)),
                ('atmp', models.IntegerField(blank=True, db_column='ATMP', null=True)),
                ('referral', models.IntegerField(blank=True, db_column='Referral', null=True)),
                ('suspension', models.IntegerField(blank=True, db_column='Suspension', null=True)),
                ('emaurl', models.CharField(blank=True, db_column='EMAURL', max_length=320, null=True)),
                ('ecurl', models.CharField(blank=True, db_column='ECURL', max_length=320, null=True)),
                ('activesubstance', models.ForeignKey(blank=True, db_column='ActiveSubstance', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lookupactivesubstance')),
                ('atccode', models.ForeignKey(blank=True, db_column='ATCCode', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lookupatccode')),
                ('legalbasis', models.ForeignKey(blank=True, db_column='LegalBasis', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lookuplegalbasis')),
                ('legalscope', models.ForeignKey(blank=True, db_column='LegalScope', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lookuplegalscope')),
                ('medicinetype', models.ForeignKey(blank=True, db_column='MedicineType', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lookupmedicinetype')),
                ('status', models.ForeignKey(blank=True, db_column='Status', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lookupstatus')),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('procedurecount', models.IntegerField(db_column='ProcedureCount')),
                ('commisionnumber', models.IntegerField(blank=True, db_column='CommisionNumber', primary_key=True, serialize=False)),
                ('emanumber', models.CharField(blank=True, db_column='EMANumber', max_length=128, null=True)),
                ('proceduredate', models.DateField(blank=True, db_column='ProcedureDate', null=True)),
                ('decisiondate', models.DateField(blank=True, db_column='DecisionDate', null=True)),
                ('decisionnumber', models.CharField(blank=True, db_column='DecisionNumber', max_length=45, null=True)),
                ('decisionurl', models.CharField(blank=True, db_column='DecisionURL', max_length=255, null=True)),
                ('annexurl', models.CharField(blank=True, db_column='AnnexURL', max_length=255, null=True)),
                ('eunumber', models.ForeignKey(db_column='EUNumber', on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
                ('proceduretype', models.ForeignKey(blank=True, db_column='ProcedureType', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lookupproceduretype')),
            ],
            options={
                'db_table': 'procedure',
                'unique_together': {('eunumber', 'procedurecount')},
            },
        ),
        migrations.CreateModel(
            name='Historyprime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prime', models.IntegerField(db_column='PRIME')),
                ('primedate', models.DateField(blank=True, db_column='PRIMEDate', null=True)),
                ('eunumber', models.ForeignKey(db_column='EUNumber', on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
            options={
                'db_table': 'historyprime',
                'unique_together': {('eunumber', 'primedate')},
            },
        ),
        migrations.CreateModel(
            name='Historyorphan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orphan', models.IntegerField(db_column='Orphan')),
                ('orphandate', models.DateField(blank=True, db_column='OrphanDate', null=True)),
                ('eunumber', models.ForeignKey(db_column='EUNumber', on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
            options={
                'db_table': 'historyorphan',
                'unique_together': {('eunumber', 'orphandate')},
            },
        ),
        migrations.CreateModel(
            name='Historymah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mah', models.CharField(db_column='MAH', max_length=255)),
                ('mahdate', models.DateField(blank=True, db_column='MAHDate', null=True)),
                ('eunumber', models.ForeignKey(db_column='EUNumber', on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
            options={
                'db_table': 'historymah',
                'unique_together': {('eunumber', 'mahdate')},
            },
        ),
        migrations.CreateModel(
            name='Historyindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication', models.CharField(db_column='Indication', max_length=45)),
                ('indicationdate', models.DateField(blank=True, db_column='IndicationDate', null=True)),
                ('eunumber', models.ForeignKey(db_column='EUNumber', on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
            options={
                'db_table': 'historyindication',
                'unique_together': {('eunumber', 'indicationdate')},
            },
        ),
        migrations.CreateModel(
            name='Historybrandname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(db_column='BrandName', max_length=255)),
                ('brandnamedate', models.DateField(blank=True, db_column='BrandNameDate', null=True)),
                ('eunumber', models.ForeignKey(db_column='EUNumber', on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
            options={
                'db_table': 'historybrandname',
                'unique_together': {('eunumber', 'brandnamedate')},
            },
        ),
        migrations.CreateModel(
            name='Historyauthorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorisationdate', models.DateField(db_column='AuthorisationDate')),
                ('opiniondate', models.DateField(blank=True, db_column='OpinionDate', null=True)),
                ('decisionauthorisationtype', models.CharField(blank=True, db_column='DecisionAuthorisationType', max_length=45, null=True)),
                ('annexauthorisationtype', models.CharField(blank=True, db_column='AnnexAuthorisationType', max_length=45, null=True)),
                ('registerauthorisationtype', models.CharField(blank=True, db_column='RegisterAuthorisationType', max_length=45, null=True)),
                ('eunumber', models.ForeignKey(db_column='EUNumber', on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
            options={
                'db_table': 'historyauthorisation',
                'unique_together': {('eunumber', 'authorisationdate')},
            },
        ),
        migrations.CreateModel(
            name='Authorisation',
            fields=[
                ('eunumber', models.OneToOneField(db_column='EUNumber', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.medicine')),
                ('acceleratedgranted', models.IntegerField(blank=True, db_column='AcceleratedGranted', null=True)),
                ('acceleratedmaintained', models.IntegerField(blank=True, db_column='AcceleratedMaintained', null=True)),
                ('authorisationtotaltime', models.IntegerField(blank=True, db_column='AuthorisationTotalTime', null=True)),
                ('authorisationactivetime', models.IntegerField(blank=True, db_column='AuthorisationActiveTime', null=True)),
                ('authorisationstoppedtime', models.IntegerField(blank=True, db_column='AuthorisationStoppedTime', null=True)),
                ('decisiontime', models.IntegerField(blank=True, db_column='DecisionTime', null=True)),
                ('decisionurl', models.CharField(blank=True, db_column='DecisionURL', max_length=255, null=True)),
                ('annexurl', models.CharField(blank=True, db_column='AnnexURL', max_length=255, null=True)),
                ('eparurl', models.CharField(blank=True, db_column='EPARURL', max_length=255, null=True)),
                ('corapporteur', models.ForeignKey(blank=True, db_column='CoRapporteur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corapporteur_related', to='api.lookuprapporteur')),
                ('rapporteur', models.ForeignKey(blank=True, db_column='Rapporteur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapporteur_related', to='api.lookuprapporteur')),
            ],
            options={
                'db_table': 'authorisation',
            },
        ),
    ]
