# Generated by Django 4.0.7 on 2022-10-19 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('eu_pnumber', models.CharField(db_column='eu_pnumber', max_length=255, primary_key=True, serialize=False)),
                ('active_substance', models.TextField(db_column='active_substance')),
                ('eu_nas', models.BooleanField(db_column='eu_nas', null=True)),
                ('ema_procedure_start_initial', models.DateField(db_column='ema_procedure_start_initial')),
                ('chmp_opinion_date', models.DateField(db_column='chmp_opinion_date')),
                ('eu_aut_date', models.DateField(db_column='eu_aut_date')),
                ('eu_legal_basis', models.CharField(choices=[('article 4.8', 'Article48'), ('article 4(8)', 'Article4 8'), ('article 4.8(1)', 'Article48 1'), ('article 4.8(2)', 'Article48 2'), ('article 4.8(3)', 'Article48 3'), ('article 8.3', 'Article83'), ('article 8(3)', 'Article8 3'), ('article 10.1', 'Article101'), ('article 10(1)', 'Article10 1'), ('article 10.2', 'Article102'), ('article 10(2)', 'Article10 2'), ('article 10.3', 'Article103'), ('article 10(3)', 'Article10 3'), ('article 10.4', 'Article104'), ('article 10(4)', 'Article10 4'), ('article 10a', 'Article10A'), ('article 10(a)', 'Article10 A'), ('article 10b', 'Article10B'), ('article 10(b)', 'Article10 B'), ('article 10c', 'Article10C'), ('article 10(c)', 'Article10 C')], db_column='eu_legal_basis', max_length=14)),
                ('ema_url', models.URLField(db_column='ema_url')),
                ('ec_url', models.URLField(db_column='ec_url')),
                ('ema_number', models.CharField(db_column='ema_number', max_length=255)),
                ('eu_med_type', models.TextField(db_column='eu_med_type')),
                ('eu_atmp', models.BooleanField(db_column='eu_atmp', null=True)),
                ('aut_url', models.URLField(db_column='aut_url')),
                ('smpc_url', models.URLField(db_column='smpc_url')),
                ('epar_url', models.URLField(db_column='epar_url')),
                ('ema_number_check', models.BooleanField(db_column='ema_number_check', null=True)),
                ('ema_rapp', models.TextField(db_column='ema_rapp')),
                ('ema_corapp', models.TextField(db_column='ema_corapp')),
                ('eu_accel_assess_g', models.BooleanField(db_column='eu_accel_assess_g', null=True)),
                ('eu_accel_assess_m', models.BooleanField(db_column='eu_accel_assess_m', null=True)),
                ('assess_time_days_total', models.IntegerField(db_column='assess_time_days_total')),
                ('assess_time_days_active', models.IntegerField(db_column='assess_time_days_active')),
                ('assess_time_days_cstop', models.IntegerField(db_column='assess_time_days_cstop')),
                ('ec_decision_time_days', models.IntegerField(db_column='ec_decision_time_days')),
                ('ema_reexamination', models.BooleanField(db_column='ema_reexamination')),
                ('eu_referral', models.BooleanField(db_column='eu_referral')),
                ('eu_suspension', models.BooleanField(db_column='eu_suspension')),
                ('omar_url', models.URLField(db_column='omar_url')),
                ('odwar_url', models.URLField(db_column='odwar_url')),
                ('eu_od_number', models.CharField(db_column='eu_od_number', max_length=255)),
                ('ema_od_number', models.CharField(db_column='ema_od_number', max_length=255)),
                ('eu_od_con', models.TextField(db_column='eu_od_con')),
                ('eu_od_date', models.DateField(db_column='eu_od_date')),
                ('eu_od_pnumber', models.CharField(db_column='eu_od_pnumber', max_length=255)),
                ('eu_od_sponsor', models.TextField(db_column='eu_od_sponsor')),
                ('eu_od_comp_date', models.DateField(db_column='eu_od_comp_date')),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
        migrations.CreateModel(
            name='SavedSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eu_numbers', models.ManyToManyField(to='api.medicine')),
            ],
            options={
                'db_table': 'saved_selection',
            },
        ),
        migrations.CreateModel(
            name='HistoryPrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(db_column='change_date', null=True)),
                ('eu_prime', models.BooleanField(db_column='eu_prime', null=True)),
                ('eu_pnumber', models.ForeignKey(db_column='eu_pnumber', on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
            options={
                'db_table': 'history_prime',
            },
        ),
        migrations.CreateModel(
            name='HistoryOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(db_column='change_date', null=True)),
                ('eu_od', models.BooleanField(db_column='eu_od', null=True)),
                ('eu_pnumber', models.ForeignKey(db_column='eu_pnumber', on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
            options={
                'db_table': 'history_od',
            },
        ),
        migrations.CreateModel(
            name='HistoryMAH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(db_column='change_date', null=True)),
                ('eu_mah', models.CharField(db_column='eu_mah', max_length=255)),
                ('eu_pnumber', models.ForeignKey(db_column='eu_pnumber', on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
            options={
                'db_table': 'eu_mah_history',
            },
        ),
        migrations.CreateModel(
            name='HistoryEUOrphanCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(db_column='change_date', null=True)),
                ('eu_orphan_con', models.TextField(db_column='eu_orphan_con')),
                ('eu_pnumber', models.ForeignKey(db_column='eu_pnumber', on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
            options={
                'db_table': 'history_eu_orphan_con',
            },
        ),
        migrations.CreateModel(
            name='HistoryBrandName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(db_column='change_date', null=True)),
                ('eu_brand_name', models.TextField(db_column='eu_brand_name')),
                ('eu_pnumber', models.ForeignKey(db_column='eu_pnumber', on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
            options={
                'db_table': 'history_brand_name',
            },
        ),
        migrations.CreateModel(
            name='HistoryAuthorisationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(db_column='change_date', null=True)),
                ('eu_aut_type', models.CharField(choices=[('CONDITIONAL', 'Conditional'), ('EXCEPTIONAL', 'Exceptional'), ('STANDARD', 'Standard')], db_column='eu_aut_type', max_length=11)),
                ('eu_pnumber', models.ForeignKey(db_column='eu_pnumber', on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
            options={
                'db_table': 'history_authorisation_type',
            },
        ),
        migrations.CreateModel(
            name='HistoryAuthorisationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(db_column='change_date', null=True)),
                ('eu_aut_status', models.CharField(choices=[('ACTIVE', 'Active'), ('WITHDRAWAL', 'Withdrawal'), ('REFUSALS', 'Refusals')], db_column='eu_aut_status', max_length=10)),
                ('eu_pnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
            options={
                'db_table': 'history_authorisation_status',
            },
        ),
        migrations.CreateModel(
            name='HistoryATCCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(db_column='change_date', null=True)),
                ('atc_code', models.CharField(db_column='atc_code', max_length=7)),
                ('eu_pnumber', models.ForeignKey(db_column='eu_pnumber', on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
            options={
                'db_table': 'history_atc_code',
            },
        ),
    ]
