# Generated by Django 4.0.8 on 2022-10-09 13:21

import api.models.medicine_models.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medisee',
            fields=[
                ('atc_code', models.CharField(db_column='atc_code', max_length=7)),
                ('active_substance', models.TextField(db_column='active_substance')),
                ('eu_nas', models.BooleanField(db_column='eu_nas', null=True)),
                ('ema_procedure_start_initial', models.DateField(db_column='ema_procedure_start_initial')),
                ('chmp_opinion_date', models.DateField(db_column='chmp_opinion_date')),
                ('eu_aut_date', models.DateField(db_column='eu_aut_date')),
                ('eu_aut_type_initial', api.models.medicine_models.common.NotVarCharField(choices=[('C', 'Conditional'), ('E', 'Exceptional'), ('S', 'Standard')], db_column='eu_aut_type_initial', max_length=1)),
                ('eu_brand_name_initial', models.TextField(db_column='eu_brand_name_initial')),
                ('eu_pnumber', models.CharField(db_column='eu_pnumber', max_length=255, primary_key=True, serialize=False)),
                ('eu_pnumber_id', models.PositiveSmallIntegerField(db_column='eu_pnumber_id')),
                ('eu_legal_basis', models.CharField(choices=[('article 4.8', 'Article48'), ('article 4(8)', 'Article4 8'), ('article 4.8(1)', 'Article48 1'), ('article 4.8(2)', 'Article48 2'), ('article 4.8(3)', 'Article48 3'), ('article 8.3', 'Article83'), ('article 8(3)', 'Article8 3'), ('article 10.1', 'Article101'), ('article 10(1)', 'Article10 1'), ('article 10.2', 'Article102'), ('article 10(2)', 'Article10 2'), ('article 10.3', 'Article103'), ('article 10(3)', 'Article10 3'), ('article 10.4', 'Article104'), ('article 10(4)', 'Article10 4'), ('article 10a', 'Article10A'), ('article 10(a)', 'Article10 A'), ('article 10b', 'Article10B'), ('article 10(b)', 'Article10 B'), ('article 10c', 'Article10C'), ('article 10(c)', 'Article10 C')], db_column='eu_legal_basis', max_length=14)),
                ('aut_url', models.URLField(db_column='aut_url')),
                ('smpc_url', models.URLField(db_column='smpc_url')),
                ('epar_url', models.URLField(db_column='epar_url')),
                ('eu_atmp', models.BooleanField(db_column='eu_atmp', null=True)),
                ('eu_med_type', models.TextField(db_column='eu_med_type')),
                ('eu_brand_name', models.TextField(db_column='eu_brand_name')),
                ('eu_brand_name_history', models.TextField(db_column='eu_brand_name_history')),
                ('ema_number', models.CharField(db_column='ema_number', max_length=255)),
                ('ema_number_id', models.PositiveSmallIntegerField(db_column='ema_number_id')),
                ('ema_number_certainty', models.FloatField(db_column='ema_number_certainty')),
                ('eu_mah', models.CharField(db_column='eu_mah', max_length=255)),
                ('eu_mah_initial', models.CharField(db_column='eu_mah_initial', max_length=255)),
                ('eu_prime_initial', models.BooleanField(db_column='eu_prime_initial', null=True)),
                ('eu_od_initial', models.BooleanField(db_column='eu_od_initial', null=True)),
                ('ema_url', models.URLField(db_column='ema_url')),
                ('ec_url', models.URLField(db_column='ec_url')),
            ],
            options={
                'db_table': 'medisee',
            },
        ),
    ]
