# Generated by Django 4.0.3 on 2022-05-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historyprime',
            unique_together={('eunumber', 'prime')},
        ),
    ]
