# Generated by Django 4.0.3 on 2022-05-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historybrandname',
            name='brandname',
            field=models.CharField(db_column='BrandName', max_length=255),
        ),
        migrations.AlterField(
            model_name='historymah',
            name='mah',
            field=models.CharField(db_column='MAH', max_length=255),
        ),
    ]
