# Generated by Django 4.0.7 on 2022-10-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_historyauthorisationstatus_eu_pnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='aut_url',
            field=models.URLField(db_column='aut_url', default='youtube.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='epar_url',
            field=models.URLField(db_column='epar_url', default='google.nl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='smpc_url',
            field=models.URLField(db_column='smpc_url', default='nu.nl'),
            preserve_default=False,
        ),
    ]
