# Generated by Django 4.0.7 on 2022-10-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_medicine_aut_url_medicine_epar_url_medicine_smpc_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='ema_number_check',
            field=models.BooleanField(db_column='eu_number_check', null=True),
        ),
        migrations.DeleteModel(
            name='HistoryEMANumberCheck',
        ),
    ]
