# Generated by Django 4.0.7 on 2022-09-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_medicine_manually_updated_procedure_manually_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='test',
            field=models.CharField(blank=True, db_column='test', max_length=45, null=True),
        ),
    ]
