# Generated by Django 4.0.7 on 2022-09-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_medicine_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorisation',
            name='corapporteur',
            field=models.ForeignKey(blank=True, db_column='CoRapporteur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corapporteur_related', to='api.medicine'),
        ),
        migrations.AlterField(
            model_name='authorisation',
            name='rapporteur',
            field=models.ForeignKey(blank=True, db_column='Rapporteur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapporteur_related', to='api.medicine'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='activesubstance',
            field=models.CharField(db_column='ActiveSubstance', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='atccode',
            field=models.CharField(db_column='ATCCode', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='legalbasis',
            field=models.CharField(db_column='LegalBasis', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='legalscope',
            field=models.CharField(db_column='LegalScope', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicinetype',
            field=models.CharField(db_column='MedicineType', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='status',
            field=models.CharField(db_column='Status', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='proceduretype',
            field=models.CharField(db_column='ProcedureType', max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Lookupactivesubstance',
        ),
        migrations.DeleteModel(
            name='Lookupatccode',
        ),
        migrations.DeleteModel(
            name='Lookuplegalbasis',
        ),
        migrations.DeleteModel(
            name='Lookuplegalscope',
        ),
        migrations.DeleteModel(
            name='Lookupmedicinetype',
        ),
        migrations.DeleteModel(
            name='Lookupproceduretype',
        ),
        migrations.DeleteModel(
            name='Lookuprapporteur',
        ),
        migrations.DeleteModel(
            name='Lookupstatus',
        ),
    ]
