# Generated by Django 4.0.7 on 2022-10-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_medicine_ema_number_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='ema_number_check',
            field=models.BooleanField(db_column='ema_number_check', null=True),
        ),
    ]
