from api.models.atc_code import AtcCode
from api.models.component import Component
from api.models.legal_basis import LegalBasis
from api.models.legal_scope import LegalScope
from api.models.marketing_authorisation_holder import MarketingAuthorisationHolder
from api.models.medicine import Medicine
from api.models.medicine_name import MedicineName
from api.models.procedure import Procedure
from api.models.procedure_type import ProcedureType
from api.models.region import Region
from api.models.substance import Substance
