export function eligibleVariablesVisualizations() {
  return [
    'BrandName',
    'MAH',
    'ActiveSubstance',
    'DecisionDate',
    'DecisionYear',
    'ATCCodeL2',
    'ApplicationNo',
    'EUNoShort',
    'Rapporteur',
    'CoRapporteur',
    'ATMP',
    'OrphanDesignation',
    'NASQualified',
    'PRIME',
    'LegalSCope',
    'LegalType',
    'AcceleratedGranted',
    'AcceleratedExecuted',
    'ActiveTimeElapsed',
    'ClockStopElapsed',
    'TotalTimeElapsed',
  ]
}
