# metadata attributes in json files
meta_file_date = "file_date"
pdf_file = "pdf_file"
xml_file = "xml_file"
is_initial = "is_initial"
creation_date = "creation_date"
modification_date = "modification_date"
filename = "filename"

# used for attribute objects
atc_code = "atc_code"
active_substance = "active_substance"
eu_nas = "eu_nas"
ema_procedure_start_initial = "ema_procedure_start_initial"
chmp_opinion_date = "chmp_opinion_date"
eu_aut_date = "eu_aut_date"
eu_aut_type_initial = "eu_aut_type_initial"
eu_aut_type_current = "eu_aut_type_current"
eu_pnumber = "eu_pnumber"
eu_legal_basis = "eu_legal_basis"
aut_url = "aut_url"
smpc_url = "smpc_url"
epar_url = "epar_url"
annex10_url = "annex10_url"    #TODO: not in docs
eu_atmp = "eu_atmp"
eu_med_type = "eu_med_type"
eu_aut_status = "eu_aut_status"
eu_brand_name_current = "eu_brand_name_current"
eu_brand_name_initial = "eu_brand_name_initial"
ema_number = "ema_number"
ema_number_id = "ema_number_id"
ema_number_certainty = "ema_number_certainty"
ema_number_check = "ema_number_check"
eu_mah_current = "eu_mah_current"
eu_mah_initial = "eu_mah_initial"
eu_prime_initial = "eu_prime_initial"
eu_od_initial = "eu_od_initial"
ema_url = "ema_url"
ec_url = "ec_url"
ema_rapp = "ema_rapp"
ema_corapp = "ema_corapp"
eu_accel_assess_g = "eu_accel_assess_g"
eu_accel_assess_m = "eu_accel_assess_m"
assess_time_days_total = "assess_time_days_total"
assess_time_days_active = "assess_time_days_active"
assess_time_days_cstop = "assess_time_days_cstop"
ec_decision_time_days = "ec_decision_time_days"
ema_reexamination = "ema_reexamination"
eu_orphan_con_current = "eu_orphan_con_current"
eu_referral = "eu_referral"
eu_suspension = "eu_suspension"
omar_url = "omar_url"
odwar_url = "odwar_url"
eu_od_number = "eu_od_number"
ema_od_number = "ema_od_number"
eu_od_con = "eu_od_con"
eu_od_date = "eu_od_date"
eu_od_pnumber = "eu_od_pnumber"
eu_od_sponsor = "eu_od_sponsor"
eu_od_comp_date = "eu_od_comp_date"
eu_od_prevalence = "eu_od_prevalence"
eu_od_alt_treatment = "eu_od_alt_treatment"
eu_od_sig_benefit = "eu_od_sig_benefit"
eu_od_roi = "eu_od_roi"
eu_procedures_todo = "eu_procedures_todo"
eu_indication_initial = "eu_indication_initial"
ema_report_date = "ema_report_date"
ema_omar_condition = "ema_omar_condition"
orphan_status = "orphan_status"


# relevant for combiner
scrape_date_web = "scrape_date_web"
filedates_web = "filedates"


# relevant for webscraper
init_addressed_to_member_states = "init_addressed_to_member_states"
other_ema_urls = "other_ema_urls"
