from .atc_code import AtcCode
from .component import Component
from .legal_basis import LegalBasis
from .legal_scope import LegalScope
from .marketing_authorisation_holder import MarketingAuthorisationHolder
from .medicine import Medicine
from .medicine_name import MedicineName
from .procedure import Procedure
from .procedure_type import ProcedureType
from .region import Region
from .substance import Substance
