name: Deploy dev backend environment

on:
  workflow_dispatch:
  push:
    branches:
      - development
    paths:
      - medctrl-backend

jobs:
  checkout:
    runs-on: deploy_backend_ci

    steps:
      - uses: actions/checkout@v2

  build_deploy:
    uses: Rutgerdj/med-ctrl/.github/workflows/backend_deploy_reusable.yml@master
    with:
      build_name: development
