name: Deploy dev backend environment

on:
  workflow_dispatch:
  push:

jobs:
  checkout:
    runs-on: deploy_backend_ci

    steps:
      - uses: actions/checkout@v2

      - name: Print status
        run: echo "done"

  build_deploy:
    uses: Rutgerdj/med-ctrl/.github/workflows/backend_deploy_reusable.yml@deploy-environments-ci
    with:
      build_name: development
