# This program has been developed by students from the bachelor Computer Science at
# Utrecht University within the Software Project course.
# © Copyright Utrecht University (Department of Information and Computing Sciences)
name: Deploy live backend environment

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - backend/**

jobs:
  checkout:
    runs-on: deploy_backend_ci

    steps:
      - uses: actions/checkout@v2

  build_deploy:
    uses: Rutgerdj/med-ctrl/.github/workflows/backend_deploy_reusable.yml@master
    with:
      build_name: live
