name: CI

on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Build using Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.python-version }}
          
      - name: install dependencies [pip]
        run: |
          python -m pip install pip --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .
          
      - name: Test with unittest
        run: python -m unittest discover -s ./test -p 'test_*.py'
