on:
  workflow_dispatch

name: Generate Sphinx Docs


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Generate Backend Docs
      working-directory: medctrl-backend/API
      run: |
            python -m pip install --upgrade pip
            pip install -r ../requirements.txt
            make html -C docs
