on:
  workflow_dispatch

name: Generate Sphinx Docs

env:
  SECRET_KEY: notsecret
  DB_USERNAME: root
  DB_PASSWORD: 1234
  DB_HOST: 127.0.0.1
  DB_DATABASE: mydatabase

jobs:
  build:
    runs-on: ubuntu-22.04
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ env.DB_DATABASE }}
        ports: ['3306:3306']
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install Dependencies
      working-directory: medctrl-backend/API
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ../requirements.txt
    - name: Set up API
      working-directory: medctrl-backend/API
      run: |
        python manage.py makemigrations api
        python manage.py migrate
        python manage.py create_column_permissions
        python manage.py createsuperuser
        python manage.py init_setup
      env: 
        DB_PORT: ${{ job.services.mysql.ports['3306'] }}
    - name: Generate Sphinx Docs
      working-directory: medctrl-backend/API
      run: make html -C docs
      env: 
        DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        
