on:
  workflow_dispatch

name: Generate Sphinx Docs

env:
  SECRET_KEY: 'notsecret'
  DB_USERNAME: 'developer' 
  DB_PASSWORD: '1234'
  DB_HOST: '127.0.0.1'
  DB_PORT: '3800'
  DB_DATABASE: 'mydatabase'
  DB_ROOT_PASSWORD: '1234'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Set up MYSQL Database
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: ${{ env.DB_PORT }}
        mysql database: ${{ env.DB_DATABASE }}
        mysql root password: ${{ env.DB_ROOT_PASSWORD }}
        mysql user: ${{ env.DB_USERNAME }}
        mysql password: ${{ env.DB_PASSWORD }}
    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping --host=$DB_HOST --password=$DB_ROOT_PASSWORD --silent; do
          sleep 1
        done
    - name: Generate Backend Docs
      working-directory: medctrl-backend/API
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ../requirements.txt
        make html -C docs
