# This program has been developed by students from the bachelor Computer Science at
# Utrecht University within the Software Project course.
# © Copyright Utrecht University (Department of Information and Computing Sciences)
name: Deploy live frontend environment

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - medctrl-frontend/**

jobs:
  checkout:
    runs-on: self-hosted-1

    steps:
      - uses: actions/checkout@v2

  deploy:
    uses: Rutgerdj/med-ctrl/.github/workflows/frontend_deploy_reusable.yml@master
    with:
      public_url: /site
      deploy_path: /var/www/medctrl/site
