name: Deploy development frontend environment

on:
  workflow_dispatch:
  push:


jobs:
  checkout:
    runs-on: self-hosted-1

    steps:
      - uses: actions/checkout@v2

      - name: Print status
        run: echo "done"

  deploy:
    uses: Rutgerdj/med-ctrl/.github/workflows/frontend_deploy_reusable.yml@deploy-environments-ci
    with:
      public_url: /dev
      deploy_path: /var/www/medctrl/dev
