name: Check for linting and formatting errors

on:
  pull_request:
    paths:
      - "medctrl-backed/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black
          pip install -r requirements.txt
        working-directory: medctrl-backend

      - name: Check code formatting with Black
        run: |
          black --diff -v .
        working-directory: medctrl-backend/API/

      - name: Analysing the code with Pylint
        run: |
          pylint $(git ls-files '**/*.py')
        working-directory: medctrl-backend/API/
