name: Integration tests using selenium

on:
  pull_request:
    paths: 
      - "medctrl-frontend/**"
      - "selenium/**"
      - ".github/workflows/system_selenium_test.yml"

env:
  NODE_VERSION: "16.x"

jobs:
  build:
    runs-on: selenium-tests
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Setup Python
        run: |
          python3.10 -m pip install --upgrade pip
          python3.10 -m pip install virtualenv
          python3.10 -m virtualenv virtualenv


      - name: Install python dependencies
        run: |
          source ../virtualenv/bin/activate
          cp /etc/medctrl/config/dev_settings.py API/api_settings/settings/
          pip install -r requirements.txt
        working-directory: "medctrl-backend"

      - name: Run python server
        run: |
          source ../virtualenv/bin/activate
          cd API/
          python manage.py runserver
        working-directory: "medctrl-backend"


      - name: Install dependencies
        run: |
          npm install
        working-directory: "medctrl-frontend"

      - name: Run frontend
        run: |
          npm start &
        working-directory: "medctrl-frontend"

      - name: Install dependencies
        run: |
          source ../virtualenv/bin/activate
          pip install -r requirements.txt
        working-directory: "selenium"

      - name: Run Tests
        run: |
          source ../virtualenv/bin/activate
          cd Tests
          python -m unittest -v
        working-directory: "selenium"
